dist: bionic
language: node_js
install:
  - for dir in plugins/*/; do (cd $dir && npm install); done
  - npm install
node_js:
- lts/*
- node
branches:
  except:
  - /^dependabot\/.*$/
script:
- npm test
- npm run build
