dist: bionic
language: node_js
install:
  - for dir in plugins/*/; do (cd $dir && npm ci); done
  - npm ci
node_js:
- lts/*
- node
branches:
  except:
  - /^dependabot\/.*$/
if: tag IS blank
script:
- npm test
- npm run build
