on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build

  deploy:
    if: github.event_name	== 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx now --token $ZEIT_TOKEN -s $ZEIT_SCOPE -n $ZEIT_NAME
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
          ZEIT_SCOPE: ${{ secrets.ZEIT_SCOPE }}
          ZEIT_NAME: ${{ secrets.ZEIT_NAME }}

  deployToProduction:
    if: github.event_name	== 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [test, deploy]
    steps:
      - uses: actions/checkout@v2
      - run: npx now --prod --token $ZEIT_TOKEN -s $ZEIT_SCOPE -n $ZEIT_NAME
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
          ZEIT_SCOPE: ${{ secrets.ZEIT_SCOPE }}
          ZEIT_NAME: ${{ secrets.ZEIT_NAME }}
